package vu.lt.mybatis.model;

public class Itemlisting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEMLISTING.ID
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEMLISTING.QUANTITY
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEMLISTING.ITEM_ID
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEMLISTING.SHOP_ID
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    private Integer shopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEMLISTING.ID
     *
     * @return the value of PUBLIC.ITEMLISTING.ID
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEMLISTING.ID
     *
     * @param id the value for PUBLIC.ITEMLISTING.ID
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEMLISTING.QUANTITY
     *
     * @return the value of PUBLIC.ITEMLISTING.QUANTITY
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEMLISTING.QUANTITY
     *
     * @param quantity the value for PUBLIC.ITEMLISTING.QUANTITY
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEMLISTING.ITEM_ID
     *
     * @return the value of PUBLIC.ITEMLISTING.ITEM_ID
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEMLISTING.ITEM_ID
     *
     * @param itemId the value for PUBLIC.ITEMLISTING.ITEM_ID
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEMLISTING.SHOP_ID
     *
     * @return the value of PUBLIC.ITEMLISTING.SHOP_ID
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEMLISTING.SHOP_ID
     *
     * @param shopId the value for PUBLIC.ITEMLISTING.SHOP_ID
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }
}