package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Item;

@Mapper
public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    List<Item> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    int updateByPrimaryKey(Item record);
}