package vu.lt.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.mybatis.model.Itemlisting;

@Mapper
public interface ItemlistingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMLISTING
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMLISTING
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    int insert(Itemlisting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMLISTING
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    Itemlisting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMLISTING
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    List<Itemlisting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEMLISTING
     *
     * @mbg.generated Wed May 29 15:35:21 EEST 2019
     */
    int updateByPrimaryKey(Itemlisting record);
}